const actionTypes = {
  LOAD_USER: "LOAD_USER",
  LOAD_TOKEN: "LOAD_TOKEN",
  LOAD_REPOLIST: "LOAD_REPOLIST",
  LOAD_FILTER_REPOLIST: "LOAD_FILTER_REPOLIST",
  RESET_FILTERED_REPOLIST: "RESET_FILTERED_REPOLIST",
  RESET_USER: "RESET_USER",
  RESET_ERROR: "RESET_ERROR",
  LOAD_ERROR: "LOAD_ERROR",
  USER_NOTFOUND: "USER_NOTFOUND",
  CREATE_REPO_ERROR: "CREATE_REPO_ERROR",
  REQUEST_SUCCESS: "REQUEST_SUCCESS",
  RESET_MESSAGE: "RESET_MESSAGE",
};

export default actionTypes;
